# Generated by Django 5.2.4 on 2025-08-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_comment_media_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='comments/'),
        ),
    ]
